version: "3.8"
services:

  fr24feed:
    build: .
    container_name: fr24feed
    restart: always
    volumes:
      - /var/log/fr24feed:/var/log/fr24feed
    devices:
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - 8754:8754
      - 30002:30002
      - 30003:30003
    entrypoint: ["fr24feed"]
